"""Streamlit replay visualizer for AeroGuard-MAS simulation events.

The GUI is intentionally a read-only viewer: all intelligent behavior is produced by
the Kotlin/Jason/tuProlog/STRIPS core and exported as JSONL events. This module loads
those events, validates them, and renders an interactive replay with aircraft positions,
routes, waypoints, conflicts, weather zones, altitude profiles, BDI traces, explanations,
and raw event tables.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from validate_events import (
    EventValidationError,
    JsonEvent,
    group_events_by_type,
    load_jsonl_events,
    validate_events,
)


SAMPLE_EVENTS_DIR = Path(__file__).parent / "sample_events"
MIN_VERTICAL_SEPARATION_FT = 1000


def main() -> None:
    """Run the Streamlit application.

    The function configures the page, loads events from the sidebar, validates the JSONL
    payload, creates the tick selector, and dispatches rendering to the main GUI tabs.
    It exits early with user-friendly messages when no file is selected or validation
    fails.
    """
    st.set_page_config(
        page_title="AeroGuard-MAS Visualizer",
        layout="wide",
    )

    st.title("AeroGuard-MAS - Event Replay Visualizer")
    st.caption(
        "Replay GUI for JSONL events generated by the Kotlin/Jason/Prolog/STRIPS core."
    )

    events = _load_events_from_sidebar()
    if events is None:
        _render_empty_state()
        return

    validation = validate_events(events)

    if not validation.valid:
        st.error("The selected JSONL file is not valid.")
        with st.expander("Validation errors", expanded=True):
            for error in validation.errors:
                st.write(f"- {error}")
        return

    if validation.warnings:
        with st.expander("Validation warnings"):
            for warning in validation.warnings:
                st.write(f"- {warning}")

    df = pd.DataFrame(events)
    grouped = group_events_by_type(events)
    ticks = sorted(df["tick"].dropna().astype(int).unique().tolist())

    if not ticks:
        st.warning("No ticks found in the selected file.")
        return

    selected_tick = st.sidebar.slider(
        "Simulation tick",
        min_value=min(ticks),
        max_value=max(ticks),
        value=min(ticks),
        step=1,
    )

    _render_summary(validation, selected_tick)

    map_tab, timeline_tab, agents_tab, explanation_tab, raw_tab = st.tabs(
        [
            "2D Map",
            "Timeline",
            "Agents & BDI",
            "Explanations",
            "Raw Events",
        ]
    )

    with map_tab:
        _render_map_tab(df, grouped, selected_tick)

    with timeline_tab:
        _render_timeline_tab(df, grouped, selected_tick)

    with agents_tab:
        _render_agents_tab(df, grouped, selected_tick)

    with explanation_tab:
        _render_explanation_tab(df, grouped, selected_tick)

    with raw_tab:
        _render_raw_events_tab(df)


def _load_events_from_sidebar() -> list[JsonEvent] | None:
    """Load JSONL events from a bundled sample file or an uploaded file.

    The sidebar supports two input modes: selecting a file from ``sample_events`` or
    uploading a custom JSONL/JSON file generated by the Kotlin core. Uploaded files are
    written to a temporary file because the validation helper expects a filesystem path.

    Returns:
        A list of JSON event dictionaries when loading succeeds, otherwise ``None``.
    """
    st.sidebar.header("Input events")

    sample_files = sorted(SAMPLE_EVENTS_DIR.glob("*.jsonl"))
    sample_names = ["None"] + [path.name for path in sample_files]

    selected_sample = st.sidebar.selectbox(
        "Load sample events",
        sample_names,
        index=1 if len(sample_names) > 1 else 0,
    )

    uploaded_file = st.sidebar.file_uploader(
        "Or upload JSONL events",
        type=["jsonl", "json"],
    )

    try:
        if uploaded_file is not None:
            with tempfile.NamedTemporaryFile(
                    delete=False,
                    suffix=".jsonl",
            ) as tmp:
                tmp.write(uploaded_file.getvalue())
                tmp_path = Path(tmp.name)

            events = load_jsonl_events(tmp_path)
            st.sidebar.success(f"Loaded uploaded file: {uploaded_file.name}")
            return events

        if selected_sample != "None":
            sample_path = SAMPLE_EVENTS_DIR / selected_sample
            events = load_jsonl_events(sample_path)
            st.sidebar.success(f"Loaded sample: {selected_sample}")
            return events

        return None

    except EventValidationError as exc:
        st.sidebar.error(str(exc))
        return None


def _render_empty_state() -> None:
    """Render the initial help panel shown before an event file is selected."""
    st.info("Choose a sample JSONL file or upload events generated by the Kotlin core.")

    st.markdown(
        """
        Expected workflow:

        ```bash
        ./gradlew run --args="--scenario scenarios/simple_conflict.json --events build/aeroguard/events/simple_conflict_events.jsonl --explain"
        ```

        Then upload the generated `.jsonl` file here.
        """
    )


def _render_summary(validation: Any, selected_tick: int) -> None:
    """Render high-level metrics for the loaded replay.

    Args:
        validation: Validation result returned by ``validate_events``.
        selected_tick: Tick currently selected by the sidebar slider.
    """
    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Events", validation.event_count)
    col2.metric("Tick", selected_tick)
    col3.metric("Min tick", validation.min_tick)
    col4.metric("Max tick", validation.max_tick)

    st.caption(f"Event types: {validation.type_counts}")


def _render_map_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    """Render the main 2D airspace replay tab.

    The tab shows the current aircraft positions, route trails, planned waypoints,
    weather zones, conflict markers, maneuver tables, and vertical-separation summaries.

    Args:
        df: DataFrame containing all loaded events.
        grouped: Events grouped by event type.
        selected_tick: Tick currently selected by the user.
    """
    st.subheader("2D Airspace Map")

    aircraft_df = _aircraft_states_at_tick(df, selected_tick)
    conflicts_df = _events_df(grouped.get("conflict_detected", []))
    maneuvers_df = _events_df(grouped.get("maneuver_selected", []))
    weather_df = _events_df(grouped.get("weather_zone_activated", []))
    routes_df = _events_df(grouped.get("route_snapshot", []))

    left, right = st.columns([2, 1])

    with left:
        if aircraft_df.empty:
            st.warning("No aircraft state events available for this tick.")
        else:
            fig = _build_aircraft_map_figure(
                df=df,
                aircraft_df=aircraft_df,
                conflicts_df=conflicts_df,
                weather_df=weather_df,
                routes_df=routes_df,
                selected_tick=selected_tick,
            )

            st.plotly_chart(fig, width="stretch")

            _render_altitude_profile(df, selected_tick)
            _render_vertical_separation_profile(df, selected_tick)

    with right:
        st.markdown("### Aircraft at tick")
        if aircraft_df.empty:
            st.write("No aircraft.")
        else:
            _show_dataframe(
                aircraft_df[
                    [
                        "aircraft",
                        "x",
                        "y",
                        "altitude",
                        "speed",
                        "status",
                        "priority",
                    ]
                ]
            )
            _render_vertical_separation_summary(aircraft_df)

        st.markdown("### Maneuvers")
        tick_maneuvers = _events_at_or_before_tick(maneuvers_df, selected_tick)
        if tick_maneuvers.empty:
            st.write("No maneuver selected yet.")
        else:
            _show_dataframe(tick_maneuvers)

        st.markdown("### Weather zones")
        visible_weather = _events_at_or_before_tick(weather_df, selected_tick)
        if visible_weather.empty:
            st.write("No active weather-zone events yet.")
        else:
            _show_dataframe(visible_weather)


def _render_timeline_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    """Render event counts, conflicts, plans, replanning events, and tick details.

    Args:
        df: DataFrame containing all loaded events.
        grouped: Events grouped by event type.
        selected_tick: Tick currently selected by the user.
    """
    st.subheader("Timeline")

    type_counts_by_tick = (
        df.groupby(["tick", "type"])
        .size()
        .reset_index(name="count")
        .sort_values(["tick", "type"])
    )

    if not type_counts_by_tick.empty:
        fig = px.bar(
            type_counts_by_tick,
            x="tick",
            y="count",
            color="type",
            title="Events per tick",
        )
        st.plotly_chart(fig, width="stretch")

    conflicts = _events_df(grouped.get("conflict_detected", []))
    plans = _events_df(grouped.get("plan_generated", []))
    replanning = _events_df(grouped.get("replanning_triggered", []))
    routes = _events_df(grouped.get("route_snapshot", []))

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### Conflicts")
        if conflicts.empty:
            st.write("No conflicts.")
        else:
            _show_dataframe(conflicts)

    with col2:
        st.markdown("### Plans")
        if plans.empty:
            st.write("No plans.")
        else:
            _show_dataframe(plans)

    st.markdown("### Replanning")
    if replanning.empty:
        st.write("No replanning events.")
    else:
        _show_dataframe(replanning)

    st.markdown("### Latest route snapshots")
    latest_routes = _latest_route_snapshots(routes, selected_tick)
    if latest_routes.empty:
        st.write("No route snapshot events.")
    else:
        _show_dataframe(latest_routes)

    st.markdown("### Events at selected tick")
    tick_df = df[df["tick"] == selected_tick].copy()
    _show_dataframe(tick_df)


def _render_agents_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    """Render BDI-oriented observability panels for the simulated agents.

    Belief updates come directly from JSONL events, while intentions are inferred from
    plan and maneuver events to make the agent workflow readable during the demo.

    Args:
        df: DataFrame containing all loaded events.
        grouped: Events grouped by event type.
        selected_tick: Tick currently selected by the user.
    """
    st.subheader("Agents & BDI Trace")

    beliefs = _events_df(grouped.get("belief_update", []))
    plans = _events_df(grouped.get("plan_generated", []))
    maneuvers = _events_df(grouped.get("maneuver_selected", []))

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### Belief updates")
        if beliefs.empty:
            st.write("No belief updates.")
        else:
            _show_dataframe(_events_at_or_before_tick(beliefs, selected_tick))

    with col2:
        st.markdown("### Intentions inferred from plans/maneuvers")
        inferred = _build_agent_intentions(plans, maneuvers, selected_tick)
        if inferred.empty:
            st.write("No inferred intentions yet.")
        else:
            _show_dataframe(inferred)

    st.markdown("### Agent responsibility summary")
    st.table(
        pd.DataFrame(
            [
                {
                    "agent": "conflict_detector",
                    "responsibility": "Detects current and predicted loss of separation.",
                },
                {
                    "agent": "sector_controller",
                    "responsibility": "Coordinates conflict handling and selected plans.",
                },
                {
                    "agent": "resolution_planner",
                    "responsibility": "Produces STRIPS resolution and replanning plans.",
                },
                {
                    "agent": "explanation_agent",
                    "responsibility": "Explains symbolic and planning decisions.",
                },
            ]
        )
    )


def _render_explanation_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    """Render explanation events available up to the selected tick.

    Args:
        df: DataFrame containing all loaded events.
        grouped: Events grouped by event type.
        selected_tick: Tick currently selected by the user.
    """
    st.subheader("Explainability")

    explanations = _events_df(grouped.get("explanation", []))
    if explanations.empty:
        st.write("No explanation events.")
        return

    visible_explanations = _events_at_or_before_tick(explanations, selected_tick)

    if visible_explanations.empty:
        st.info("No explanations available yet at this tick.")
        return

    for _, row in visible_explanations.iterrows():
        st.markdown(f"**Tick {row.get('tick')} — {row.get('agent', 'unknown_agent')}**")
        st.write(row.get("message", ""))


def _render_raw_events_tab(df: pd.DataFrame) -> None:
    """Render the raw JSONL event table with filtering and CSV export.

    Args:
        df: DataFrame containing all loaded events.
    """
    st.subheader("Raw JSONL events")

    event_type_filter = st.multiselect(
        "Filter by event type",
        options=sorted(df["type"].dropna().unique().tolist()),
        default=sorted(df["type"].dropna().unique().tolist()),
    )

    filtered = df[df["type"].isin(event_type_filter)] if event_type_filter else df

    _show_dataframe(filtered)

    csv = _arrow_safe_dataframe(filtered).to_csv(index=False).encode("utf-8")
    st.download_button(
        label="Download filtered events as CSV",
        data=csv,
        file_name="aeroguard_filtered_events.csv",
        mime="text/csv",
    )


def _aircraft_states_at_tick(df: pd.DataFrame, tick: int) -> pd.DataFrame:
    """Return aircraft states for the selected tick.

    If no exact aircraft-state event exists at the requested tick, the latest known state
    at or before the tick is returned for each aircraft. This keeps the replay usable even
    when some event types are sparse.

    Args:
        df: DataFrame containing all loaded events.
        tick: Tick to inspect.

    Returns:
        DataFrame containing the current aircraft states.
    """
    aircraft_df = df[df["type"] == "aircraft_state"].copy()

    if aircraft_df.empty:
        return aircraft_df

    exact_tick = aircraft_df[aircraft_df["tick"] == tick].copy()
    if not exact_tick.empty:
        return exact_tick.sort_values("aircraft")

    previous = aircraft_df[aircraft_df["tick"] <= tick].copy()
    if previous.empty:
        return previous

    previous = previous.sort_values(["aircraft", "tick"])
    return previous.groupby("aircraft").tail(1).sort_values("aircraft")


def _build_aircraft_map_figure(
        df: pd.DataFrame,
        aircraft_df: pd.DataFrame,
        conflicts_df: pd.DataFrame,
        weather_df: pd.DataFrame,
        routes_df: pd.DataFrame,
        selected_tick: int,
) -> go.Figure:
    """Build the Plotly figure for the 2D aircraft map.

    The figure combines historical trails, planned route snapshots, aircraft labels,
    conflict lines, and active weather zones.

    Args:
        df: DataFrame containing all loaded events.
        aircraft_df: Aircraft states visible at the selected tick.
        conflicts_df: Conflict events.
        weather_df: Weather-zone activation events.
        routes_df: Route snapshot events.
        selected_tick: Tick currently selected by the user.

    Returns:
        A configured Plotly figure ready for Streamlit rendering.
    """
    plot_df = _aircraft_display_positions(aircraft_df)

    fig = go.Figure()

    _add_aircraft_trails(fig, df, selected_tick)
    _add_route_snapshots(fig, routes_df, aircraft_df, selected_tick)

    for _, row in plot_df.iterrows():
        aircraft = row["aircraft"]
        altitude = row["altitude"]
        speed = row["speed"]
        status = row["status"]
        priority = row["priority"]

        hover_text = (
            f"<b>{aircraft}</b><br>"
            f"Position: ({float(row['x']):.2f}, {float(row['y']):.2f})<br>"
            f"Altitude: {altitude} ft<br>"
            f"Speed: {speed}<br>"
            f"Status: {status}<br>"
            f"Priority: {priority}"
        )

        fig.add_trace(
            go.Scatter(
                x=[row["display_x"]],
                y=[row["display_y"]],
                mode="text",
                text=["✈"],
                textfont={"size": 28},
                name=str(aircraft),
                hovertext=[hover_text],
                hoverinfo="text",
                showlegend=True,
            )
        )

        fig.add_trace(
            go.Scatter(
                x=[row["display_x"]],
                y=[row["display_y"] + row["label_offset"]],
                mode="text",
                text=[f"{aircraft}<br>{altitude} ft"],
                textfont={"size": 11},
                name=f"{aircraft} label",
                hoverinfo="skip",
                showlegend=False,
            )
        )

    _add_conflict_lines(fig, plot_df, conflicts_df, selected_tick)
    _add_weather_zones(fig, weather_df, selected_tick)

    fig.update_layout(
        title=f"Aircraft positions at tick {selected_tick}",
        xaxis_title="X",
        yaxis_title="Y",
        yaxis_scaleanchor="x",
        height=600,
    )

    return fig


def _aircraft_display_positions(aircraft_df: pd.DataFrame) -> pd.DataFrame:
    """Add display-only offsets for aircraft sharing the same 2D position.

    The real ``x`` and ``y`` columns are preserved. New ``display_x`` and ``display_y``
    columns are used only for plotting, so overlapping aircraft remain visible without
    altering the simulation data.

    Args:
        aircraft_df: Aircraft state DataFrame.

    Returns:
        Copy of the aircraft DataFrame enriched with display coordinates.
    """
    if aircraft_df.empty:
        return aircraft_df

    plot_df = aircraft_df.copy()

    x_span = max(float(plot_df["x"].max() - plot_df["x"].min()), 1.0)
    y_span = max(float(plot_df["y"].max() - plot_df["y"].min()), 1.0)
    offset = min(x_span, y_span) * 0.035

    plot_df["position_key"] = plot_df.apply(
        lambda row: f"{round(float(row['x']), 3)}:{round(float(row['y']), 3)}",
        axis=1,
    )

    plot_df["display_x"] = plot_df["x"].astype(float)
    plot_df["display_y"] = plot_df["y"].astype(float)
    plot_df["label_offset"] = offset * 1.6

    for _, group in plot_df.groupby("position_key"):
        if len(group) == 1:
            continue

        group_indices = list(group.index)
        center = (len(group_indices) - 1) / 2.0

        for local_index, dataframe_index in enumerate(group_indices):
            relative_index = local_index - center
            plot_df.loc[dataframe_index, "display_x"] = (
                    float(plot_df.loc[dataframe_index, "x"]) + relative_index * offset
            )
            plot_df.loc[dataframe_index, "display_y"] = (
                    float(plot_df.loc[dataframe_index, "y"]) + relative_index * offset
            )

    return plot_df


def _add_aircraft_trails(
        fig: go.Figure,
        df: pd.DataFrame,
        selected_tick: int,
) -> None:
    """Draw historical aircraft trails up to the selected tick.

    Args:
        fig: Plotly figure to update.
        df: DataFrame containing all loaded events.
        selected_tick: Tick currently selected by the user.
    """
    history = df[
        (df["type"] == "aircraft_state")
        & (df["tick"] <= selected_tick)
        ].copy()

    if history.empty:
        return

    for aircraft, aircraft_history in history.groupby("aircraft"):
        aircraft_history = aircraft_history.sort_values("tick")

        fig.add_trace(
            go.Scatter(
                x=aircraft_history["x"],
                y=aircraft_history["y"],
                mode="lines",
                name=f"{aircraft} trail",
                line={"dash": "solid", "width": 2},
                hoverinfo="skip",
                showlegend=True,
            )
        )


def _add_route_snapshots(
        fig: go.Figure,
        routes_df: pd.DataFrame,
        aircraft_df: pd.DataFrame,
        selected_tick: int,
) -> None:
    """Draw current planned routes and waypoint markers.

    The function uses the latest ``route_snapshot`` event at or before the selected tick
    for each aircraft. If the Kotlin core applied a reroute, the displayed route changes
    accordingly.

    Args:
        fig: Plotly figure to update.
        routes_df: Route snapshot events.
        aircraft_df: Aircraft states visible at the selected tick.
        selected_tick: Tick currently selected by the user.
    """
    if routes_df.empty:
        return

    visible_routes = routes_df[routes_df["tick"] <= selected_tick].copy()

    if visible_routes.empty:
        return

    visible_routes = visible_routes.sort_values(["aircraft", "tick"])
    latest_routes = visible_routes.groupby("aircraft").tail(1)

    current_positions = {
        row["aircraft"]: (float(row["x"]), float(row["y"]))
        for _, row in aircraft_df.iterrows()
        if "aircraft" in row and "x" in row and "y" in row
    }

    for _, route in latest_routes.iterrows():
        aircraft = route.get("aircraft")
        waypoints = route.get("waypoints")

        if not isinstance(aircraft, str):
            continue

        if not isinstance(waypoints, list) or not waypoints:
            continue

        route_xs: list[float] = []
        route_ys: list[float] = []
        waypoint_xs: list[float] = []
        waypoint_ys: list[float] = []
        waypoint_labels: list[str] = []

        if aircraft in current_positions:
            current_x, current_y = current_positions[aircraft]
            route_xs.append(current_x)
            route_ys.append(current_y)

        for waypoint in waypoints:
            if not isinstance(waypoint, dict):
                continue

            x = waypoint.get("x")
            y = waypoint.get("y")
            name = waypoint.get("name", "WP")

            if not isinstance(x, (int, float)):
                continue

            if not isinstance(y, (int, float)):
                continue

            route_xs.append(float(x))
            route_ys.append(float(y))
            waypoint_xs.append(float(x))
            waypoint_ys.append(float(y))
            waypoint_labels.append(str(name))

        if not waypoint_xs:
            continue

        fig.add_trace(
            go.Scatter(
                x=route_xs,
                y=route_ys,
                mode="lines",
                name=f"{aircraft} planned route",
                line={"dash": "dash", "width": 2},
                hoverinfo="skip",
                showlegend=True,
            )
        )

        fig.add_trace(
            go.Scatter(
                x=waypoint_xs,
                y=waypoint_ys,
                mode="markers+text",
                text=waypoint_labels,
                textposition="bottom center",
                name=f"{aircraft} waypoints",
                marker={"symbol": "diamond", "size": 10},
                hovertext=[
                    f"{aircraft} waypoint {label}"
                    for label in waypoint_labels
                ],
                hoverinfo="text",
                showlegend=True,
            )
        )


def _add_conflict_lines(
        fig: go.Figure,
        aircraft_df: pd.DataFrame,
        conflicts_df: pd.DataFrame,
        selected_tick: int,
) -> None:
    """Draw conflict lines between aircraft involved in conflicts at the selected tick.

    Args:
        fig: Plotly figure to update.
        aircraft_df: Aircraft states or display-position DataFrame.
        conflicts_df: Conflict events.
        selected_tick: Tick currently selected by the user.
    """
    if conflicts_df.empty or aircraft_df.empty:
        return

    visible_conflicts = conflicts_df[conflicts_df["tick"] == selected_tick].copy()

    x_column = "display_x" if "display_x" in aircraft_df.columns else "x"
    y_column = "display_y" if "display_y" in aircraft_df.columns else "y"

    positions = {
        row["aircraft"]: (row[x_column], row[y_column])
        for _, row in aircraft_df.iterrows()
        if "aircraft" in row and x_column in row and y_column in row
    }

    for _, conflict in visible_conflicts.iterrows():
        aircraft_ids = conflict.get("aircraft")
        if not isinstance(aircraft_ids, list) or len(aircraft_ids) < 2:
            continue

        first, second = aircraft_ids[0], aircraft_ids[1]
        if first not in positions or second not in positions:
            continue

        x0, y0 = positions[first]
        x1, y1 = positions[second]

        fig.add_trace(
            go.Scatter(
                x=[x0, x1],
                y=[y0, y1],
                mode="lines",
                name=f"conflict {first}-{second}",
                line={"dash": "dash", "width": 2},
            )
        )


def _add_weather_zones(
        fig: go.Figure,
        weather_df: pd.DataFrame,
        selected_tick: int,
) -> None:
    """Draw active weather zones as circular overlays on the 2D map.

    Args:
        fig: Plotly figure to update.
        weather_df: Weather-zone activation events.
        selected_tick: Tick currently selected by the user.
    """
    if weather_df.empty:
        return

    visible_weather = _events_at_or_before_tick(weather_df, selected_tick)

    for _, zone in visible_weather.iterrows():
        x = zone.get("x")
        y = zone.get("y")
        radius = zone.get("radius")
        name = zone.get("zone", "weather_zone")

        if not isinstance(x, (int, float)):
            continue
        if not isinstance(y, (int, float)):
            continue
        if not isinstance(radius, (int, float)):
            continue

        fig.add_shape(
            type="circle",
            xref="x",
            yref="y",
            x0=x - radius,
            y0=y - radius,
            x1=x + radius,
            y1=y + radius,
            line={"dash": "dot", "width": 2},
        )

        fig.add_trace(
            go.Scatter(
                x=[x],
                y=[y],
                mode="text",
                text=[str(name)],
                name=str(name),
                showlegend=False,
            )
        )


def _render_altitude_profile(df: pd.DataFrame, selected_tick: int) -> None:
    """Render a zoomed altitude profile for all aircraft up to the selected tick.

    The y-axis is automatically narrowed around the observed altitude range so small
    vertical changes, such as a 2,000 ft climb, are visible in the demo.

    Args:
        df: DataFrame containing all loaded events.
        selected_tick: Tick currently selected by the user.
    """
    aircraft_history = df[
        (df["type"] == "aircraft_state")
        & (df["tick"] <= selected_tick)
        ].copy()

    if aircraft_history.empty:
        return

    st.markdown("### Altitude profile")

    min_altitude = int(aircraft_history["altitude"].min())
    max_altitude = int(aircraft_history["altitude"].max())

    if min_altitude == max_altitude:
        y_min = min_altitude - 500
        y_max = max_altitude + 500
    else:
        altitude_span = max_altitude - min_altitude
        margin = max(250, int(altitude_span * 0.15))
        y_min = min_altitude - margin
        y_max = max_altitude + margin

    fig = px.line(
        aircraft_history,
        x="tick",
        y="altitude",
        color="aircraft",
        markers=True,
        title="Aircraft altitude over time",
    )
    fig.update_layout(
        xaxis_title="Tick",
        yaxis_title="Altitude / Flight level",
        height=320,
    )
    fig.update_yaxes(
        range=[y_min, y_max],
        dtick=500,
        tickformat=",d",
    )

    st.plotly_chart(fig, width="stretch")


def _render_vertical_separation_profile(df: pd.DataFrame, selected_tick: int) -> None:
    """Render vertical separation over time for every aircraft pair.

    The chart includes the minimum vertical-separation threshold as a reference line.

    Args:
        df: DataFrame containing all loaded events.
        selected_tick: Tick currently selected by the user.
    """
    aircraft_history = df[
        (df["type"] == "aircraft_state")
        & (df["tick"] <= selected_tick)
        ].copy()

    if aircraft_history.empty:
        return

    rows: list[dict[str, Any]] = []

    for tick, tick_df in aircraft_history.groupby("tick"):
        aircraft_rows = tick_df.to_dict("records")

        for index, first in enumerate(aircraft_rows):
            for second in aircraft_rows[index + 1:]:
                vertical_distance = abs(
                    int(first["altitude"]) - int(second["altitude"])
                )

                rows.append(
                    {
                        "tick": int(tick),
                        "aircraft_pair": f"{first['aircraft']} / {second['aircraft']}",
                        "vertical_distance_ft": vertical_distance,
                    }
                )

    if not rows:
        return

    separation_df = pd.DataFrame(rows)

    st.markdown("### Vertical separation profile")

    max_distance = int(separation_df["vertical_distance_ft"].max())
    y_max = max(2500, max_distance + 250)

    fig = px.line(
        separation_df,
        x="tick",
        y="vertical_distance_ft",
        color="aircraft_pair",
        markers=True,
        title="Vertical separation over time",
    )

    fig.add_hline(
        y=MIN_VERTICAL_SEPARATION_FT,
        line_dash="dash",
        annotation_text=f"Minimum vertical separation: {MIN_VERTICAL_SEPARATION_FT} ft",
        annotation_position="top left",
    )

    fig.update_layout(
        xaxis_title="Tick",
        yaxis_title="Vertical separation / ft",
        height=300,
    )
    fig.update_yaxes(
        range=[0, y_max],
        dtick=500,
        tickformat=",d",
    )

    st.plotly_chart(fig, width="stretch")


def _render_vertical_separation_summary(aircraft_df: pd.DataFrame) -> None:
    """Render pairwise horizontal and vertical separation for the current tick.

    Args:
        aircraft_df: Aircraft states visible at the selected tick.
    """
    if aircraft_df.empty or len(aircraft_df) < 2:
        return

    rows: list[dict[str, Any]] = []
    aircraft_rows = aircraft_df.to_dict("records")

    for index, first in enumerate(aircraft_rows):
        for second in aircraft_rows[index + 1:]:
            dx = float(first["x"]) - float(second["x"])
            dy = float(first["y"]) - float(second["y"])
            horizontal_distance = (dx**2 + dy**2) ** 0.5

            vertical_distance = abs(
                int(first["altitude"]) - int(second["altitude"])
            )

            rows.append(
                {
                    "aircraft_pair": f"{first['aircraft']} / {second['aircraft']}",
                    "horizontal_distance": round(horizontal_distance, 2),
                    "vertical_distance_ft": vertical_distance,
                    "status": (
                        "separated vertically"
                        if vertical_distance >= MIN_VERTICAL_SEPARATION_FT
                        else "vertical conflict risk"
                    ),
                }
            )

    if not rows:
        return

    st.markdown("### Separation summary")
    _show_dataframe(pd.DataFrame(rows))


def _latest_route_snapshots(
        routes_df: pd.DataFrame,
        selected_tick: int,
) -> pd.DataFrame:
    """Return the latest route snapshot for each aircraft at or before the tick.

    Args:
        routes_df: Route snapshot events.
        selected_tick: Tick currently selected by the user.

    Returns:
        DataFrame containing at most one route snapshot per aircraft.
    """
    if routes_df.empty:
        return routes_df

    visible_routes = routes_df[routes_df["tick"] <= selected_tick].copy()
    if visible_routes.empty:
        return visible_routes

    return visible_routes.sort_values(["aircraft", "tick"]).groupby("aircraft").tail(1)


def _events_df(events: list[JsonEvent]) -> pd.DataFrame:
    """Convert a list of events to a DataFrame sorted by tick.

    Args:
        events: JSON event dictionaries.

    Returns:
        Sorted DataFrame, or an empty DataFrame when no events are provided.
    """
    if not events:
        return pd.DataFrame()

    return pd.DataFrame(events).sort_values("tick")


def _events_at_or_before_tick(df: pd.DataFrame, selected_tick: int) -> pd.DataFrame:
    """Filter an event DataFrame to events visible at the selected tick.

    Args:
        df: Event DataFrame.
        selected_tick: Tick currently selected by the user.

    Returns:
        Filtered copy of the DataFrame.
    """
    if df.empty or "tick" not in df.columns:
        return df

    return df[df["tick"] <= selected_tick].copy()


def _build_agent_intentions(
        plans: pd.DataFrame,
        maneuvers: pd.DataFrame,
        selected_tick: int,
) -> pd.DataFrame:
    """Infer a compact intention table from plan and maneuver events.

    This is a visualization helper rather than a reasoning component. The real BDI logic
    remains in the Jason agents and Kotlin event stream.

    Args:
        plans: Plan-generated events.
        maneuvers: Maneuver-selected events.
        selected_tick: Tick currently selected by the user.

    Returns:
        DataFrame with inferred agent intentions.
    """
    rows: list[dict[str, Any]] = []

    visible_plans = _events_at_or_before_tick(plans, selected_tick)
    visible_maneuvers = _events_at_or_before_tick(maneuvers, selected_tick)

    for _, row in visible_plans.iterrows():
        actions = row.get("actions")
        if isinstance(actions, list):
            detail = ", ".join(str(action) for action in actions)
        else:
            detail = str(actions) if actions is not None else ""

        rows.append(
            {
                "tick": row.get("tick"),
                "agent": "resolution_planner",
                "intention": f"generate plan for {row.get('aircraft')}",
                "detail": detail,
            }
        )

    for _, row in visible_maneuvers.iterrows():
        maneuver = row.get("maneuver")
        target_altitude = row.get("targetAltitude")

        if pd.notna(target_altitude):
            detail = f"{maneuver} targetAltitude={target_altitude}"
        else:
            detail = str(maneuver) if maneuver is not None else ""

        rows.append(
            {
                "tick": row.get("tick"),
                "agent": "sector_controller",
                "intention": f"select maneuver for {row.get('aircraft')}",
                "detail": detail,
            }
        )

    return pd.DataFrame(rows)


def _arrow_safe_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Convert mixed object columns to display-safe strings for Streamlit.

    PyArrow cannot serialize columns mixing lists, dictionaries, and scalar values. This
    helper keeps the original data model intact and only stringifies complex cells for
    rendering.

    Args:
        df: DataFrame to render.

    Returns:
        Arrow-compatible DataFrame copy.
    """
    if df.empty:
        return df

    safe = df.copy()

    for column in safe.columns:
        if safe[column].dtype == "object":
            safe[column] = safe[column].map(_format_cell_for_display)

    return safe


def _format_cell_for_display(value: Any) -> str:
    """Format one arbitrary cell value for safe table display.

    Args:
        value: Cell value to format.

    Returns:
        String representation suitable for Streamlit/PyArrow.
    """
    if isinstance(value, list):
        return json.dumps(value, ensure_ascii=False)

    if isinstance(value, (tuple, set)):
        return ", ".join(str(item) for item in value)

    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False)

    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass

    return str(value)


def _show_dataframe(df: pd.DataFrame, *, hide_index: bool = True) -> None:
    """Render a DataFrame after converting complex cells to Arrow-safe strings.

    Args:
        df: DataFrame to show.
        hide_index: Whether Streamlit should hide the DataFrame index.
    """
    st.dataframe(
        _arrow_safe_dataframe(df),
        width="stretch",
        hide_index=hide_index,
    )


if __name__ == "__main__":
    main()
