from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from validate_events import (
    EventValidationError,
    JsonEvent,
    group_events_by_type,
    load_jsonl_events,
    validate_events,
)


SAMPLE_EVENTS_DIR = Path(__file__).parent / "sample_events"


def main() -> None:
    st.set_page_config(
        page_title="AeroGuard-MAS Visualizer",
        layout="wide",
    )

    st.title("AeroGuard-MAS - Event Replay Visualizer")
    st.caption(
        "Replay GUI for JSONL events generated by the Kotlin/Jason/Prolog/STRIPS core."
    )

    events = _load_events_from_sidebar()
    if events is None:
        _render_empty_state()
        return

    validation = validate_events(events)

    if not validation.valid:
        st.error("The selected JSONL file is not valid.")
        with st.expander("Validation errors", expanded=True):
            for error in validation.errors:
                st.write(f"- {error}")
        return

    if validation.warnings:
        with st.expander("Validation warnings"):
            for warning in validation.warnings:
                st.write(f"- {warning}")

    df = pd.DataFrame(events)
    grouped = group_events_by_type(events)
    ticks = sorted(df["tick"].dropna().astype(int).unique().tolist())

    if not ticks:
        st.warning("No ticks found in the selected file.")
        return

    selected_tick = st.sidebar.slider(
        "Simulation tick",
        min_value=min(ticks),
        max_value=max(ticks),
        value=min(ticks),
        step=1,
    )

    _render_summary(validation, selected_tick)

    map_tab, timeline_tab, agents_tab, explanation_tab, raw_tab = st.tabs(
        [
            "2D Map",
            "Timeline",
            "Agents & BDI",
            "Explanations",
            "Raw Events",
        ]
    )

    with map_tab:
        _render_map_tab(df, grouped, selected_tick)

    with timeline_tab:
        _render_timeline_tab(df, grouped, selected_tick)

    with agents_tab:
        _render_agents_tab(df, grouped, selected_tick)

    with explanation_tab:
        _render_explanation_tab(df, grouped, selected_tick)

    with raw_tab:
        _render_raw_events_tab(df)


def _load_events_from_sidebar() -> list[JsonEvent] | None:
    st.sidebar.header("Input events")

    sample_files = sorted(SAMPLE_EVENTS_DIR.glob("*.jsonl"))
    sample_names = ["None"] + [path.name for path in sample_files]

    selected_sample = st.sidebar.selectbox(
        "Load sample events",
        sample_names,
        index=1 if len(sample_names) > 1 else 0,
    )

    uploaded_file = st.sidebar.file_uploader(
        "Or upload JSONL events",
        type=["jsonl", "json"],
    )

    try:
        if uploaded_file is not None:
            with tempfile.NamedTemporaryFile(
                    delete=False,
                    suffix=".jsonl",
            ) as tmp:
                tmp.write(uploaded_file.getvalue())
                tmp_path = Path(tmp.name)

            events = load_jsonl_events(tmp_path)
            st.sidebar.success(f"Loaded uploaded file: {uploaded_file.name}")
            return events

        if selected_sample != "None":
            sample_path = SAMPLE_EVENTS_DIR / selected_sample
            events = load_jsonl_events(sample_path)
            st.sidebar.success(f"Loaded sample: {selected_sample}")
            return events

        return None

    except EventValidationError as exc:
        st.sidebar.error(str(exc))
        return None


def _render_empty_state() -> None:
    st.info("Choose a sample JSONL file or upload events generated by the Kotlin core.")

    st.markdown(
        """
        Expected workflow:

        ```bash
        ./gradlew run --args="--scenario scenarios/simple_conflict.json --events build/aeroguard/events/simple_conflict_events.jsonl --explain"
        ```

        Then upload the generated `.jsonl` file here.
        """
    )


def _render_summary(validation: Any, selected_tick: int) -> None:
    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Events", validation.event_count)
    col2.metric("Tick", selected_tick)
    col3.metric("Min tick", validation.min_tick)
    col4.metric("Max tick", validation.max_tick)

    st.caption(f"Event types: {validation.type_counts}")


def _render_map_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    st.subheader("2D Airspace Map")

    aircraft_df = _aircraft_states_at_tick(df, selected_tick)
    conflicts_df = _events_df(grouped.get("conflict_detected", []))
    maneuvers_df = _events_df(grouped.get("maneuver_selected", []))

    left, right = st.columns([2, 1])

    with left:
        if aircraft_df.empty:
            st.warning("No aircraft state events available for this tick.")
        else:
            fig = px.scatter(
                aircraft_df,
                x="x",
                y="y",
                text="aircraft",
                hover_data=[
                    "aircraft",
                    "altitude",
                    "speed",
                    "status",
                    "priority",
                ],
                title=f"Aircraft positions at tick {selected_tick}",
            )
            fig.update_traces(textposition="top center", marker={"size": 14})
            fig.update_layout(
                xaxis_title="X",
                yaxis_title="Y",
                yaxis_scaleanchor="x",
                height=600,
            )

            _add_conflict_lines(fig, aircraft_df, conflicts_df, selected_tick)

            st.plotly_chart(fig, use_container_width=True)

    with right:
        st.markdown("### Aircraft at tick")
        if aircraft_df.empty:
            st.write("No aircraft.")
        else:
            st.dataframe(
                aircraft_df[
                    [
                        "aircraft",
                        "x",
                        "y",
                        "altitude",
                        "speed",
                        "status",
                        "priority",
                    ]
                ],
                use_container_width=True,
                hide_index=True,
            )

        st.markdown("### Maneuvers")
        tick_maneuvers = _events_at_or_before_tick(maneuvers_df, selected_tick)
        if tick_maneuvers.empty:
            st.write("No maneuver selected yet.")
        else:
            st.dataframe(tick_maneuvers, use_container_width=True, hide_index=True)


def _render_timeline_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    st.subheader("Timeline")

    type_counts_by_tick = (
        df.groupby(["tick", "type"])
        .size()
        .reset_index(name="count")
        .sort_values(["tick", "type"])
    )

    if not type_counts_by_tick.empty:
        fig = px.bar(
            type_counts_by_tick,
            x="tick",
            y="count",
            color="type",
            title="Events per tick",
        )
        st.plotly_chart(fig, use_container_width=True)

    conflicts = _events_df(grouped.get("conflict_detected", []))
    plans = _events_df(grouped.get("plan_generated", []))

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### Conflicts")
        if conflicts.empty:
            st.write("No conflicts.")
        else:
            st.dataframe(conflicts, use_container_width=True, hide_index=True)

    with col2:
        st.markdown("### Plans")
        if plans.empty:
            st.write("No plans.")
        else:
            st.dataframe(plans, use_container_width=True, hide_index=True)

    st.markdown("### Events at selected tick")
    tick_df = df[df["tick"] == selected_tick].copy()
    st.dataframe(tick_df, use_container_width=True, hide_index=True)


def _render_agents_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    st.subheader("Agents & BDI Trace")

    beliefs = _events_df(grouped.get("belief_update", []))
    plans = _events_df(grouped.get("plan_generated", []))
    maneuvers = _events_df(grouped.get("maneuver_selected", []))

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### Belief updates")
        if beliefs.empty:
            st.write("No belief updates.")
        else:
            st.dataframe(
                _events_at_or_before_tick(beliefs, selected_tick),
                use_container_width=True,
                hide_index=True,
            )

    with col2:
        st.markdown("### Intentions inferred from plans/maneuvers")
        inferred = _build_agent_intentions(plans, maneuvers, selected_tick)
        if inferred.empty:
            st.write("No inferred intentions yet.")
        else:
            st.dataframe(inferred, use_container_width=True, hide_index=True)

    st.markdown("### Agent responsibility summary")
    st.table(
        pd.DataFrame(
            [
                {
                    "agent": "conflict_detector",
                    "responsibility": "Detects current and predicted loss of separation.",
                },
                {
                    "agent": "sector_controller",
                    "responsibility": "Coordinates conflict handling and selected plans.",
                },
                {
                    "agent": "resolution_planner",
                    "responsibility": "Produces STRIPS resolution plans.",
                },
                {
                    "agent": "explanation_agent",
                    "responsibility": "Explains symbolic and planning decisions.",
                },
            ]
        )
    )


def _render_explanation_tab(
        df: pd.DataFrame,
        grouped: dict[str, list[JsonEvent]],
        selected_tick: int,
) -> None:
    st.subheader("Explainability")

    explanations = _events_df(grouped.get("explanation", []))
    if explanations.empty:
        st.write("No explanation events.")
        return

    visible_explanations = _events_at_or_before_tick(explanations, selected_tick)

    if visible_explanations.empty:
        st.info("No explanations available yet at this tick.")
        return

    for _, row in visible_explanations.iterrows():
        st.markdown(f"**Tick {row.get('tick')} — {row.get('agent', 'unknown_agent')}**")
        st.write(row.get("message", ""))


def _render_raw_events_tab(df: pd.DataFrame) -> None:
    st.subheader("Raw JSONL events")

    event_type_filter = st.multiselect(
        "Filter by event type",
        options=sorted(df["type"].dropna().unique().tolist()),
        default=sorted(df["type"].dropna().unique().tolist()),
    )

    filtered = df[df["type"].isin(event_type_filter)] if event_type_filter else df

    st.dataframe(filtered, use_container_width=True, hide_index=True)

    csv = filtered.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="Download filtered events as CSV",
        data=csv,
        file_name="aeroguard_filtered_events.csv",
        mime="text/csv",
    )


def _aircraft_states_at_tick(df: pd.DataFrame, tick: int) -> pd.DataFrame:
    aircraft_df = df[df["type"] == "aircraft_state"].copy()

    if aircraft_df.empty:
        return aircraft_df

    exact_tick = aircraft_df[aircraft_df["tick"] == tick].copy()
    if not exact_tick.empty:
        return exact_tick.sort_values("aircraft")

    previous = aircraft_df[aircraft_df["tick"] <= tick].copy()
    if previous.empty:
        return previous

    previous = previous.sort_values(["aircraft", "tick"])
    return previous.groupby("aircraft").tail(1).sort_values("aircraft")


def _add_conflict_lines(
        fig: go.Figure,
        aircraft_df: pd.DataFrame,
        conflicts_df: pd.DataFrame,
        selected_tick: int,
) -> None:
    if conflicts_df.empty or aircraft_df.empty:
        return

    visible_conflicts = _events_at_or_before_tick(conflicts_df, selected_tick)

    positions = {
        row["aircraft"]: (row["x"], row["y"])
        for _, row in aircraft_df.iterrows()
        if "aircraft" in row and "x" in row and "y" in row
    }

    for _, conflict in visible_conflicts.iterrows():
        aircraft_ids = conflict.get("aircraft")
        if not isinstance(aircraft_ids, list) or len(aircraft_ids) < 2:
            continue

        first, second = aircraft_ids[0], aircraft_ids[1]
        if first not in positions or second not in positions:
            continue

        x0, y0 = positions[first]
        x1, y1 = positions[second]

        fig.add_trace(
            go.Scatter(
                x=[x0, x1],
                y=[y0, y1],
                mode="lines",
                name=f"conflict {first}-{second}",
                line={"dash": "dash", "width": 2},
            )
        )


def _events_df(events: list[JsonEvent]) -> pd.DataFrame:
    if not events:
        return pd.DataFrame()

    return pd.DataFrame(events).sort_values("tick")


def _events_at_or_before_tick(df: pd.DataFrame, selected_tick: int) -> pd.DataFrame:
    if df.empty or "tick" not in df.columns:
        return df

    return df[df["tick"] <= selected_tick].copy()


def _build_agent_intentions(
        plans: pd.DataFrame,
        maneuvers: pd.DataFrame,
        selected_tick: int,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []

    visible_plans = _events_at_or_before_tick(plans, selected_tick)
    visible_maneuvers = _events_at_or_before_tick(maneuvers, selected_tick)

    for _, row in visible_plans.iterrows():
        actions = row.get("actions")
        if isinstance(actions, list):
            detail = ", ".join(str(action) for action in actions)
        else:
            detail = str(actions) if actions is not None else ""

        rows.append(
            {
                "tick": row.get("tick"),
                "agent": "resolution_planner",
                "intention": f"generate plan for {row.get('aircraft')}",
                "detail": detail,
            }
        )

    for _, row in visible_maneuvers.iterrows():
        maneuver = row.get("maneuver")
        target_altitude = row.get("targetAltitude")

        if pd.notna(target_altitude):
            detail = f"{maneuver} targetAltitude={target_altitude}"
        else:
            detail = str(maneuver) if maneuver is not None else ""

        rows.append(
            {
                "tick": row.get("tick"),
                "agent": "sector_controller",
                "intention": f"select maneuver for {row.get('aircraft')}",
                "detail": detail,
            }
        )

    return pd.DataFrame(rows)


if __name__ == "__main__":
    main()
